echo "=================================================="
echo "🚨🚨🚨 GITHUB PUSH ALERT 🚨🚨🚨"
echo "=================================================="
echo ""
echo "⚠️  LEMBRETE IMPORTANTE:"
echo "----------------------------------------------"
echo "👤 Username: seu usuário GitHub"
echo "🔑 Password: USE TOKEN (NÃO é senha normal!)"
echo ""
echo "🌐 Gerar token aqui:"
echo "https://github.com/settings/tokens"
echo ""
echo "💀 NÃO PERCA SEU TOKEN"
echo "💀 NÃO USE SENHA NORMAL"
echo "=================================================="
echo ""
